### ISSUE TITLE
vk rpi driver - vkOpenArena

### ISSUE THREAD

**Issue by Renetrox** [suijingfeng/vkOpenArena#26]
this is not a problem as such, just curious: could this driver be used with vkopenarena?
https://github.com/Yours3lf/rpi-vk-driver

**Comment by suijingfeng** [comment]
I don't have a Raspberry Pi , I could buy one and test it 
but i guess it will not be funny,  rpi-vk-driver is for the geek i think
and not easy to use and may be rich of bugs.

I am works for MIPS arch CPU currently, and really don't have much time to try and testing it.
sorry.

**Comment by Renetrox** [comment]
> I don't have a Raspberry Pi , I could buy one and test it
> but i guess it will not be funny, rpi-vk-driver is for the geek i think
> and not easy to use and may be rich of bugs.
> 
> I am works for MIPS arch CPU currently, and really don't have much time to try and testing it.
> sorry.


Thanks for your answer! It is understandable, I asked about it since I saw that they managed to run quake3 and I assumed that maybe it would be something possible with openarena, mine is curiosity more than anything!
